### ISSUE TITLE
yadage validation and absolute/relative paths

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#111]
This works:

```console
$ grep steps workflow/workflow.yml 
      step: {$ref: 'workflow/steps.yml#/eventselection'}
      step: {$ref: 'workflow/steps.yml#/statanalysis'}
$ yadage-run _run workflow/workflow.yml 
$ reana-client workflow create
```

This does not work:

```console
$ grep steps workflow/workflow.yml 
      step: {$ref: 'steps.yml#/eventselection'}
      step: {$ref: 'steps.yml#/statanalysis'}
$ yadage-run _run workflow.yml -t workflow 
$ reana-client workflow create
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana-0.2.0/lib/python3.6/site-packages/yadageschemas/__init__.py", line 156, in yamlloader
    data = urlopen(uri).read()
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1452, in file_open
    return self.open_local_file(req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1491, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/home/simko/private/project/reana/src/reana-demo-atlas-recast/steps.yml'>
Workflow could not be created: 
('RuntimeError: ', {'$ref': 'steps.yml#/eventselection'})
```

It would be good if `reana-client` discovers that `workflow.yml` is located in such and such directory and resolves links accordingly.

(stemmed from https://github.com/reanahub/reana-demo-atlas-recast/pull/1#discussion_r195935489)

**Comment by lukasheinrich** [comment]
there might be a general solution, where workflow engine-specific options can be passed to the client

e.g.

```
workflow:
  type: yadage
  file: databkgmc.yml
  options:
    toplevel: workflow
    dataopts: # (this controls the directory layout the engine plans for the individual jobs)
      nest: False 
```

we discussed a similar strategy for backend options a while back.. the engines usually allow for many cusotmizations (e.g. CWL allows setting the docker user,
