### ISSUE TITLE
client: investigate ROOT file uploading troubles

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#140]
The uploading of input ROOT files seems troublesome:

```console
$ reana-client inputs upload ./inputs/*
File /afs/cern.ch/user/s/simko/private/project/reana/src/reana-demo-cms-h4l/inputs/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt was successfully uploaded.
Something went wrong while uploading /afs/cern.ch/user/s/simko/private/project/reana/src/reana-demo-cms-h4l/inputs/DoubleE11.root
[...]
```

Note the first TXT file upload went OK, the second ROOT file upload did not succeed.

This is necessary for https://github.com/reanahub/reana-demo-cms-h4l/issues/4

**Comment by diegodelemos** [comment]
is this happening with latest master? I could reproduce it once. Right after I set some debugging breakpoints I debugged the upload of all files and everything went fine. Now every time I upload the files it works. Any hint on how to reproduce again @tiborsimko ?
P.S.

**Comment by tiborsimko** [comment]
Happens on LXPLUS-CLOUD working against REANA-QA with one-month old sources.
Note that the default Python 3 version there is Python 3.4 still...

```console
$ python -V
Python 3.4.8

$ reana-client -l DEBUG inputs upload ./inputs/ZZ4mu12.root
...
[2018-07-27 17:28:03,062] p3192 {/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/reana_client/api/client.py:505} INFO - Uploading 'ZZ4mu12.root' ...
[2018-07-27 17:28:03,062] p3192 {/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/bravado/client.py:239} DEBUG - seed_analysis_inputs({'analysis_id_or_name': 'h4l.3', 'file_name': 'ZZ4mu12.root', 'organization': 'default', 'token': 'lqvmZ3nGpPx1c6EIl5VL8DTtPwYLniIjS4AnjxlLY1c', 'file_content': <_io.TextIOWrapper name='/afs/cern.ch/user/s/simko/private/project/reana/src/reana-demo-cms-h4l/inputs/ZZ4mu12.root' mode='r' encoding='UTF-8'>})
[2018-07-27 17:28:03,067] p3192 {/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/reana_client/api/client.py:523} DEBUG - Traceback (most recent call last):
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/reana_client/api/client.py", line 514, in upload_to_server
    save_path, token)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/reana_client/api/client.py", line 230, in seed_analysis_inputs
    raise e
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/reana_client/api/client.py", line 211, in seed_analysis_inputs
    token=token).result()
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/bravado/http_future.py", line 212, in result
    incoming_response = self._get_incoming_response(timeout)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/bravado/http_future.py", line 96, in wrapper
    return func(self, *args, **kwargs)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/bravado/http_future.py", line 227, in _get_incoming_response
    inner_response = self.future.result(timeout=timeout)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/bravado/requests_client.py", line 293, in result
    prepared_request = self.session.prepare_request(request)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/requests/models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/requests/models.py", line 500, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/afs/cern.ch/user/s/simko/reana/lib64/python3.4/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte
```

**Comment by tiborsimko** [comment]
@dinosk Confirmed this is still happening for me with Python 3.6.6 and the latest `master` components:

- reana-workflow-commons @ master dfa9ce2 installation: bump Sphinx and rtd-theme min vern
- reana-server @ master 13f3136 openapi: rwc spec required fields in create_wkfl
- reana-job-controller @ master 501c2a7 api: add job_name and prettified_cmd to create_job
- reana-workflow-engine-yadage @ master 27be7df tasks: progress status renaming
- reana-workflow-engine-serial @ master afe1704 tasks: progress status renaming
- reana-workflow-controller @ master 30c5bcc rest: fix passing empty run_started_at
- reana-commons @ master ce601da models: remove WorkflowJobs
- reana-message-broker @ master 9d0bee3 docs: new logo, panel verbiage and links
- reana-workflow-monitor @ master @ 924ef8d docs: new logo, panel verbiage and links
- reana-workflow-engine-cwl @ master @ 19311e7 cwl_runner: progress status renaming

Can you please verify on your setup?

**Comment by dinosk** [comment]
Interesting, I tried it with python 3.6.6 and 2.7.15, using latest master but I couldn't reproduce:
```
(reana-3.6) ➜  reana-demo-root6-roofit git:(master) ✗ rc upload inputs
...
File inputs/ZZ4mu12.root was successfully uploaded.
File inputs/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt was successfully uploaded.
File inputs/DoubleE11.root was successfully uploaded.
...
```

**Comment by tiborsimko** [comment]
Interestingly enough I still get the "invalid continuation byte" message:

```console
$ reana-client -l DEBUG upload ./inputs
...
[2018-08-03 13:49:17,892] p669 {/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py:386} DEBUG - Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py", line 381, in upload_to_server
    save_path, access_token)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py", line 219, in upload_file
    raise e
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py", line 200, in upload_file
    access_token=access_token).result()
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/bravado/http_future.py", line 200, in result
    incoming_response = self._get_incoming_response(timeout)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/bravado/http_future.py", line 78, in wrapper
    return func(self, *args, **kwargs)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/bravado/http_future.py", line 215, in _get_incoming_response
    inner_response = self.future.result(timeout=timeout)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/bravado/requests_client.py", line 292, in result
    prepared_request = self.session.prepare_request(request)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/requests/models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/requests/models.py", line 500, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
  File "/home/simko/.virtualenvs/reana/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

[2018-08-03 13:49:17,892] p669 {/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py:387} DEBUG - 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte
[2018-08-03 13:49:17,892] p669 {/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py:389} INFO - Something went wrong while uploading HZZ11.root
[2018-08-03 13:49:17,892] p669 {/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/cli/files.py:257} DEBUG - Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/cli/files.py", line 242, in upload_files
    access_token)
  File "/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/api/client.py", line 355, in upload_to_server
    uploaded_files.extend(next_uploaded_files)
TypeError: 'NoneType' object is not iterable

[2018-08-03 13:49:17,893] p669 {/home/simko/.virtualenvs/reana/lib/python3.6/site-packages/reana_client/cli/files.py:258} DEBUG - 'NoneType' object is not iterable
```

**Comment by dinosk** [comment]
I can't get it to fail for some reason. On `reana-qa`:
```
(reana) ➜  reana-demo-root6-roofit git:(master) ✗ rc -l DEBUG inputs upload ./inputs/*

[2018-08-03 14:20:31,165] p16188 {/home/dinos/reanahub/reana-client/reana_client/api/client.py:454} INFO - Workflow "workflow.18" selected
[2018-08-03 14:20:31,165] p16188 {/home/dinos/reanahub/reana-client/reana_client/api/client.py:504} DEBUG - 'ZZ4mu12.root' is an absolute filepath.
[2018-08-03 14:20:31,165] p16188 {/home/dinos/reanahub/reana-client/reana_client/api/client.py:505} INFO - Uploading 'ZZ4mu12.root' ...
[2018-08-03 14:20:31,165] p16188 {/home/dinos/.pyenv/versions/reana/local/lib/python2.7/site-packages/bravado/client.py:239} DEBUG - seed_analysis_inputs({'file_content': <open file '/home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4mu12.root', mode 'r' at 0x7f4003027f60>, 'file_name': 'ZZ4mu12.root', 'token': u'U9S5r63GMawacSkJWCBK49yWiCUzltiicg5Vo1Co2Fo', 'analysis_id_or_name': u'workflow.18', 'organization': u'default'})
[2018-08-03 14:20:31,183] p16188 {/home/dinos/.pyenv/versions/reana/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:401} DEBUG - "POST /api/analyses/workflow.18/workspace/inputs?file_name=ZZ4mu12.root&token=U9S5r63GMawacSkJWCBK49yWiCUzltiicg5Vo1Co2Fo&organization=default HTTP/1.1" 200 44
[2018-08-03 14:20:31,184] p16188 {/home/dinos/reanahub/reana-client/reana_client/api/client.py:521} INFO - File 'ZZ4mu12.root' was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4mu12.root was successfully uploaded.
```

**Comment by diegodelemos** [comment]
> Interestingly enough I still get the "invalid continuation byte" message:

I can reproduce locally now.

### Local cluster @ master

```console
$ reana git-status
- reana-message-broker @ master
- reana-server @ master
- reana-commons @ master
- reana-workflow-controller @ master
- reana-workflow-commons @ master
- reana-workflow-engine-serial @ master
- reana-job-controller @ master
- reana-workflow-engine-cwl @ master
- reana-workflow-engine-yadage @ master
- reana-workflow-monitor @ master
```
 Python 3.6.5, `reana-client` master and [reana-demo-cms-h4l/inputs/DY50TuneZ11.root](https://github.com/reanahub/reana-demo-cms-h4l/blob/master/inputs/DY50TuneZ11.root) and I get:
```console
$ reana-client -l DEBUG upload DY50TuneZ11.root
  File "/Users/rodrigdi/.virtualenvs/r-client/bin/../lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

[2018-08-03 14:29:37,797] p51403 {/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py:387} DEBUG - 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte
[2018-08-03 14:29:37,797] p51403 {/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py:389} INFO - Something went wrong while uploading DY50TuneZ11.root
[2018-08-03 14:29:37,799] p51403 {/Users/rodrigdi/code/reana/reana-client/reana_client/cli/files.py:257} DEBUG - Traceback (most recent call last):
  File "/Users/rodrigdi/code/reana/reana-client/reana_client/cli/files.py", line 243, in upload_files
    for file_ in response:
TypeError: 'NoneType' object is not iterable

[2018-08-03 14:29:37,799] p51403 {/Users/rodrigdi/code/reana/reana-client/reana_client/cli/files.py:258} DEBUG - 'NoneType' object is not iterable
Something went wrong while uploading /Users/rodrigdi/code/reana/reana-demo-root6-roofit/DY50TuneZ11.root
Something went wrong while uploading /Users/rodrigdi/code/reana/reana-demo-root6-roofit/DY50TuneZ11.root
```

### REANA-QA and local `reana-client`

Regarding `reana-qa` I can also reproduce with [`reana-client@a41400f`](https://github.com/reanahub/reana-client/commit/a41400fa62b81138156fd86a3cba3d1565d0bfb6) and [`reana-demo-root6-roofit@b1ebc8e`](https://github.com/reanahub/reana-demo-root6-roofit/commit/b1ebc8e26d4e35ac2679b796c31b6c0d39a06185). Python 3.6.5 and same file, [reana-demo-cms-h4l/inputs/DY50TuneZ11.root](https://github.com/reanahub/reana-demo-cms-h4l/blob/master/inputs/DY50TuneZ11.root):

```console
$ reana-client -l DEBUG code upload code
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

[2018-08-03 14:51:59,098] p52154 {/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py:524} DEBUG - 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte
[2018-08-03 14:51:59,098] p52154 {/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py:526} INFO - Something went wrong while uploading DY50TuneZ11.root
[2018-08-03 14:51:59,100] p52154 {/Users/rodrigdi/code/reana/reana-client/reana_client/cli/code.py:195} DEBUG - Traceback (most recent call last):
  File "/Users/rodrigdi/code/reana/reana-client/reana_client/cli/code.py", line 175, in code_upload
    token)
  File "/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py", line 480, in upload_to_server
    upload_type, token)
  File "/Users/rodrigdi/code/reana/reana-client/reana_client/api/client.py", line 527, in upload_to_server
    return response
UnboundLocalError: local variable 'response' referenced before assignment

[2018-08-03 14:51:59,100] p52154 {/Users/rodrigdi/code/reana/reana-client/reana_client/cli/code.py:196} DEBUG - local variable 'response' referenced before assignment
Something went wrong while uploading /Users/rodrigdi/code/reana/reana-demo-root6-roofit/code
```

**Comment by diegodelemos** [comment]
@dinosk can you run:
```console
$ pip freeze | grep "requests\|bravado"
bravado==10.1.0
bravado-core==5.0.4
requests==2.19.1
```
There has been some activity later in [requests](http://docs.python-requests.org/en/master/community/updates/), [bravado](https://github.com/Yelp/bravado/blob/master/CHANGELOG.rst) and [bravado-core](https://github.com/Yelp/bravado-core/blob/master/CHANGELOG.rst) and if you didn't start a fresh virtualenv, that might be the reason.

**Comment by dinosk** [comment]
@diegodelemos I had `requests==2.11.1` but even after upgrading it is still the same:
```
(reana) ➜  reana-demo-root6-roofit git:(master) ✗ rc inputs upload inputs/*
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON.txt was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DoubleE11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DoubleE12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DoubleMu11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DoubleMu12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY1011.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY1012.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY101Jets12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY50Mag12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY50TuneZ11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DY50TuneZ12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/DYTo2mu12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/HZZ11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/HZZ12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/TTBar11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/TTBar12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/TTJets11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/TTJets12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ2mu2e11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ2mu2e12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4e11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4e12.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4mu11.root was successfully uploaded.
File /home/dinos/reanahub/reana-demo-root6-roofit/inputs/ZZ4mu12.root was successfully uploaded.
(reana) ➜  reana-demo-root6-roofit git:(master) ✗ pip freeze | grep "requests\|bravado"
bravado==10.1.0
bravado-core==5.0.4
requests==2.19.1
```
