### ISSUE TITLE
cli: fail to upload file on Python2.7

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#301]
## What happens?

When trying to upload a file using REANA-Client with Python 2.7 and there is an error while uploading, the CLI shows the following exception:

```console
Traceback (most recent call last):
  File "/home/dprelipc/.virtualenvs/myreana/bin/reana-client", line 10, in <module>
    sys.exit(cli())
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/reana_client/cli/utils.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/reana_client/cli/utils.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python2.7/site-packages/reana_client/cli/files.py", line 270, in upload_files
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined
```

## Cause

We are using the built-in exception [`FileNotFoundError`](https://docs.python.org/3/library/exceptions.html#FileNotFoundError) (in [reana_client/cli/files.py](https://github.com/reanahub/reana-client/blob/1ef17763f5babaeb89c91e316cf22a94fea58a2a/reana_client/cli/files.py#L286) and [reana_client/utils.py](https://github.com/reanahub/reana-client/blob/15831ef9c50d7b005f4190bfcd82778b3892c606/reana_client/utils.py#L323)) which is only available in Python 3.

**Comment by dprelipcean** [comment]
Related error occurs in Python 3.6 as well. This time it raises the generic error:
`Something went wrong while uploading /home/dprelipc/Documents/private/reana-demo-lhcb-d2pimumu/data/D2PiMuMuOS.root
`

**Comment by tiborsimko** [comment]
@dprelipcean Can you upload other files well?  If this occurs only for ROOT files, then it could be related to the old problem #140 (see the fix in #146) that is perhaps back...

**Comment by tiborsimko** [comment]
Confirming troubles for non-ROOT files:

```console
$ reana-client upload -w worldpopulation.serial
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana-py27/bin/reana-client", line 10, in <module>
    sys.exit(cli())
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/reana_client/cli/utils.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/reana_client/cli/utils.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/reana_client/cli/utils.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/reana_client/cli/files.py", line 237, in upload_files
    False)
  File "/home/simko/.virtualenvs/reana-py27/lib/python2.7/site-packages/reana_client/utils.py", line 150, in load_reana_spec
    raise e
AttributeError: 'module' object has no attribute 'FullLoader'
[2019-12-16T16:54:58] reana-demo-worldpopulation: Command 'reana-client upload -w worldpopulation.serial' returned non-zero exit status 1
```

**Comment by tiborsimko** [comment]
Found problem, old PyYAML coming with Python-2.7, need to up the minimal version, PR coming...
