### ISSUE TITLE
cli: error uploading a large file

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-client#302]
## What happens?
When uploading a large file (962.9 MB), the following generic error ocurs:

`Something went wrong while uploading /home/dprelipc/Documents/private/reana-demo-lhcb-d2pimumu/data/D2PiMuMuOS.root`

The full traceback is the following:
```
[2019-07-04 16:22:21,196] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado_core/model.py:790} DEBUG - Already visited id 10418848
[2019-07-04 16:22:21,197] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado_core/resource.py:95} DEBUG - Building resource 'api'
[2019-07-04 16:22:21,197] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/client.py:239} DEBUG - upload_file({'workflow_id_or_name': 'my-analysis.4', 'file_content': <_io.BufferedReader name='/home/dprelipc/Documents/private/reana-demo-lhcb-d2pimumu/data/D2PiMuMuOS.root'>, 'file_name': 'data/D2PiMuMuOS.root', 'access_token': 'njzC6vpri92pC78gJBAHkDImDBjNYBtFRhCqTx4gt_I'})
[2019-07-04 16:22:22,141] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/urllib3/connectionpool.py:815} DEBUG - Starting new HTTPS connection (1): 192.168.39.111:30443
/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2019-07-04 16:23:07,491] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/urllib3/connectionpool.py:396} DEBUG - https://192.168.39.111:30443 "POST /api/workflows/my-analysis.4/workspace?file_name=data%2FD2PiMuMuOS.root&access_token=njzC6vpri92pC78gJBAHkDImDBjNYBtFRhCqTx4gt_I HTTP/1.1" 502 11
[2019-07-04 16:23:07,496] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py:489} DEBUG - Traceback (most recent call last):
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py", line 252, in upload_file
    access_token=access_token).result()
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/http_future.py", line 302, in _get_swagger_result
    self.request_config.response_callbacks,
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/http_future.py", line 333, in unmarshal_response
    raise_on_unexpected(incoming_response)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/http_future.py", line 404, in raise_on_unexpected
    raise make_http_exception(response=http_response)
bravado.exception.HTTPBadGateway: 502 Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py", line 482, in upload_to_server
    access_token)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py", line 268, in upload_file
    e.response.json()['message']))
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/bravado/requests_client.py", line 283, in json
    return self._delegate.json(**kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2019-07-04 16:23:07,496] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py:490} DEBUG - Expecting value: line 1 column 1 (char 0)
[2019-07-04 16:23:07,496] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/api/client.py:492} INFO - Something went wrong while uploading D2PiMuMuOS.root
[2019-07-04 16:23:07,552] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/cli/files.py:293} DEBUG - Traceback (most recent call last):
  File "/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/cli/files.py", line 259, in upload_files
    for file_ in response:
TypeError: 'NoneType' object is not iterable

[2019-07-04 16:23:07,552] p7872 {/home/dprelipc/.virtualenvs/myreana/local/lib/python3.6/site-packages/reana_client/cli/files.py:294} DEBUG - 'NoneType' object is not iterable
Something went wrong while uploading /home/dprelipc/Documents/private/reana-demo-lhcb-d2pimumu/data/D2PiMuMuOS.root
```

The logs on the server side via `kubectl  logs server-7558f76d6d-pgrpn server -f
` are:
```
DAMN ! worker 1 (pid: 37) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 39)
```

## Cause
It"s possible that the cache is out of memory or requests lasts too long, see this  [post](https://github.com/unbit/uwsgi/issues/1779)

**Comment by dprelipcean** [comment]
I'm trying to `minikube mount`, but `reana-client` still does not find the file. A workaround is to mount on a `tmp` and then `scp` the file to the desired destination. This worked well with smaller (up to 1GB) file, but if I try it with a 10 GB file, then minikube crashses:
```console
$ sudo scp tmp/D2PiMuMuOS.root data/
ssh: wait: remote command exited without exit status or exit signal
```
PS.: I have allocated quite some resources, so not sure where the problem lies:
`MINIKUBE_DISKSIZE=100g MINIKUBE_MEMORY=12288 make ci`

**Comment by tiborsimko** [comment]
Seeing almost the same but without the `DAMN... respawn` message:

```console
$ reana-client upload -w lhcb-d2pimumu.cwl data/D2PiMuMuOS.root
Something went wrong while uploading /home/simko/private/project/reana/src/reana-demo-lhcb-d2pimumu/data/D2PiMuMuOS.root

$ kubectl logs server-5d576f8f66-7r89g server
[pid: 56|app: 0|req: 57/91] 172.17.0.2 () {42 vars in 910 bytes} [Wed Sep 11 11:12:57 2019] POST /api/workflows/lhcb-d2pimumu.cwl/workspace?file_name=data%2FD2PiMuMuOS.
root&access_token=Xbgt0CTVXMMdowoYmzw7VucAJaTyfoXDMt4iDSXupHA => generated 196 bytes in 1 msecs (HTTP/1.1 413) 9 headers in 446 bytes (1 switches on core 0)
```

Note HTTP status 413 => Payload Too Large.  

The test file is 962908702 bytes big.

@diegodelemos Have you looked at increasing the limits?
