### ISSUE TITLE
validate: yadage parameters

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#386]
Take `reana-demo-root6-roofit` as an example.

The workflow needs a parameter called `events`. 

If a user makes a mistake and calls this parameter `xevents`, the workflow still validates:

```console
reana-client validate -f ./reana-yadage.yaml
File reana-demo-root6-roofit/reana-yadage.yaml is a valid REANA specification file.
```

but the execution understandably fails:

```console
$ reana-client logs -w roofit-yadage
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/adage/__init__.py", line 51, in run_polling_workflow
    for stepnum, controller in enumerate(coroutine):
  File "/usr/local/lib/python3.6/site-packages/adage/pollingexec.py", line 92, in adage_coroutine
    update_dag(controller, extend_decider,recursive_updates)
  File "/usr/local/lib/python3.6/site-packages/adage/pollingexec.py", line 48, in update_dag
    update_dag(controller, decider, recurse)
  File "/usr/local/lib/python3.6/site-packages/adage/pollingexec.py", line 43, in update_dag
    update_loop.send(command)
  File "/usr/local/lib/python3.6/site-packages/adage/pollingexec.py", line 21, in update_coroutine
...
  File "/usr/local/lib/python3.6/site-packages/yadage/handlers/scheduler_handlers.py", line 200, in <dictcomp>
    for k, v in get_parameters(spec["parameters"]).items()
  File "/usr/local/lib/python3.6/site-packages/yadage/handlers/scheduler_handlers.py", line 49, in select_parameter
    value = handler(wflowview, parameter)
  File "/usr/local/lib/python3.6/site-packages/yadage/handlers/expression_handlers.py", line 161, in stage_output_selector
    step, selection.get("output"), selection_type == "scopes"
  File "/usr/local/lib/python3.6/site-packages/yadage/handlers/expression_handlers.py", line 55, in select_reference
    % (selection, step["result"])
RuntimeError: no matches found in reference selection. selection events | result <TypedLeafs: {'fitdata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/4616756d-2a10-4787-9237-3e243f83c782/code/fitdata.C', 'gendata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/4616756d-2a10-4787-9237-3e243f83c782/code/gendata.C', 'xevents': 20000}>
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/reana_workflow_engine_yadage/cli.py", line 125, in run_yadage_workflow
    REANATracker(identifier=workflow_uuid)])
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/yadage/steering_api.py", line 118, in steering_ctx
    cache=cache,
  File "/usr/local/lib/python3.6/site-packages/yadage/steering_api.py", line 60, in execute_steering
    ys.run_adage(backend)
  File "/usr/local/lib/python3.6/site-packages/yadage/steering_object.py", line 100, in run_adage
    adage.rundag(controller=self.controller, **self.adage_kwargs)
  File "/usr/local/lib/python3.6/site-packages/adage/__init__.py", line 137, in rundag
    run_polling_workflow(controller, coroutine, update_interval, trackerlist, maxsteps)
  File "/usr/local/lib/python3.6/site-packages/adage/__init__.py", line 63, in run_polling_workflow
    trackprogress(trackerlist, controller, method = 'finalize')
  File "/usr/local/lib/python3.6/site-packages/adage/__init__.py", line 30, in trackprogress
    getattr(t,method)(controller.adageobj)
  File "/usr/local/lib/python3.6/site-packages/adage/trackers.py", line 46, in finalize
    viz.print_dag(adageobj.dag,'dag_{:02}'.format(i),self.workdir,time = i/float(self.frames))
  File "/usr/local/lib/python3.6/site-packages/adage/visualize.py", line 73, in print_dag
    save_dot(colorize_graph(dag,time).to_string(),pngfilename,'png')
  File "/usr/local/lib/python3.6/site-packages/adage/visualize.py", line 28, in colorize_graph
    stop  = max(filter(lambda x: x,[dag.getNode(n).ready_by_time for n in allnodes]))
ValueError: max() arg is an empty sequence
```

Two things:

- can we improve client-side validation so that these problems would be caught?

- can we improve server-side workflow run so that no Python tracebacks would be emitted back to the user but rather a message saying "required parameter events missing"?

**Comment by tiborsimko** [comment]
The current status seems to be that the validation passes:

```console
$ sed -i 's,{events},{xevents},g' workflow/yadage/workflow.yaml
$ reana-client validate -f ./reana-yadage.yaml    
reana-yadage.yaml is a valid REANA specification file.
```

This means there is no longer traceback, but the user is given false impression that the workflow is well-defined, which it isn't.

We should warn the user similarly as in the Serial workflow, see #465.

Note: we could write a yadage parameter validator in a nice standalone-like Python function, so that it could be later submitted as a PR to improve the yadage package itself.

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/470
