### ISSUE TITLE
QA: `run` exception

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#412]
Seen on QA after upgrade:

```console
$ reana-client run -w htc -f ./reana-htcondorcern.yaml
[INFO] Creating a workflow...
htc.1
[INFO] Uploading files...
Traceback (most recent call last):
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/bin/reana-client", line 11, in <module>
    sys.exit(cli())
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/workflow.py", line 861, in workflow_run
    access_token=access_token)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/afs/cern.ch/user/s/simko/.virtualenvs/reana-qa/lib/python2.7/site-packages/reana_client/cli/files.py", line 269, in upload_files
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined
```

The same command repeated a few seconds later passed.

**Comment by diegodelemos** [comment]
Not happening any more on QA using [0.7.0-dev20200529](https://github.com/reanahub/reana/commit/d14d8f828c4f2ac9a74861d19881b459d55bda06) release and [current latest master `reana-client`](https://github.com/reanahub/reana-client/commit/44811f7f8b3f4af5711fb3813182d4d9638437fb):
```
$ reana-client run -w htc -f ./reana-htcondorcern.yaml 
[INFO] Creating a workflow...
htc.1
[INFO] Uploading files...
File /code/helloworld.py was successfully uploaded.
File /data/names.txt was successfully uploaded.
[INFO] Starting workflow...
htc.1 has been queued
```
Now we have a different problem regarding HTCondor described in https://github.com/reanahub/reana-job-controller/issues/250:
```
$ reana-client logs -w htc.1
==> Workflow engine logs
2020-06-02 09:19:53,524 | root | MainThread | INFO | Workflow 330531d8-b67b-4fb1-82e2-00af5bb1f40d failed. Files available at /var/reana/users/0ec01937-be5a-4849-a278-d7d24338dd4b/workflows/330531d8-b67b-4fb1-82e2-00af5bb1f40d.
```
