### ISSUE TITLE
validate: reana.yaml parameters vs yadage parameters

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#466]
A task similar to #386 is the mismatch between Yadage parameter names and REANA parameter names.

Take RooFit demo workflow, and make a typo on the `reana-yadage.yaml` level:

```console
$ sed -i 's,events,noevents,g' reana-yadage.yaml
```

The validation still passes:

```console
$ yadage-validate ./workflow/yadage/workflow.yaml       
workflow validates against schema

$  reana-client validate -f ./reana-yadage.yaml
reana-yadage.yaml is a valid REANA specification file.
```

We should detect the cases where the Yadage workflow itself s OK, but the `reana-yadage.yaml` refers to different parameters.

Because while the Yadage workflow would run well locally, when run through REANA, the users would see errors like:

```console
$ reana-client run -w yad -f ./reana-yadage.yaml
$ reana-client logs -w yad
2021-03-01 09:17:07,248 | yadage.handlers.expression_handlers | MainThread | INFO | matches
2021-03-01 09:17:07,249 | yadage.handlers.expression_handlers | MainThread | ERROR | no matches found for selection events in result <TypedLeafs: {'fitdata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/5f1e7138-c591-4554-8847-ead22bded8e6/code/fitdata.C', 'gendata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/5f1e7138-c591-4554-8847-ead22bded8e6/code/gendata.C', 'noevents': 20000}>
2021-03-01 09:17:07,249 | adage | MainThread | ERROR | some weird exception caught in adage process loop
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.8/site-packages/yadage/handlers/scheduler_handlers.py", line 199, in <dictcomp>
    k: select_parameter(stage.view, v)
  File "/usr/local/lib/python3.8/site-packages/yadage/handlers/scheduler_handlers.py", line 49, in select_parameter
    value = handler(wflowview, parameter)
  File "/usr/local/lib/python3.8/site-packages/yadage/handlers/expression_handlers.py", line 160, in stage_output_selector
    return select_reference(
  File "/usr/local/lib/python3.8/site-packages/yadage/handlers/expression_handlers.py", line 53, in select_reference
    raise RuntimeError(
RuntimeError: no matches found in reference selection. selection events | result <TypedLeafs: {'fitdata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/5f1e7138-c591-4554-8847-ead22bded8e6/code/fitdata.C', 'gendata': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/5f1e7138-c591-4554-8847-ead22bded8e6/code/gendata.C', 'noevents': 20000}>
```

**Comment by mvidalgarcia** [comment]
Closed by https://github.com/reanahub/reana-client/pull/470
