### ISSUE TITLE
cli: fix download traceback

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#69]
FIx traceback:

```console
$ reana-client outputs download greetings.txt
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.39.58:32075
[DEBUG] Running find_module: netrc...
[DEBUG] Running load_module for netrc...
[DEBUG] Excluded netrc from translation
[DEBUG] Running find_module: shlex...
[DEBUG] Running load_module for shlex...
[DEBUG] Excluded shlex from translation
[WARNING] Failed to parse headers (url=http://192.168.39.58:32075/api/analyses/a9329917-5888-44a2-b57e-b7f882799d20/workspace/outputs/greetings.txt?user=00000000-0000-0000-0000-000000000000&organization=default): [NoBoundaryInMultipartDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/reana-client-py3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/simko/.virtualenvs/reana-client-py3/lib/python3.6/site-packages/urllib3/util/response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [NoBoundaryInMultipartDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
[INFO] greetings.txt binary file downloaded ... writing to ./outputs/
File greetings.txt downloaded to ./outputs/
```

**Comment by tiborsimko** [comment]
(stemmed from https://github.com/reanahub/reana-demo-helloworld/pull/17#issuecomment-367746296)

**Comment by diegodelemos** [comment]
This is only happening with Python 3:

```console
$ workon reana-client
$ python --version
Python 3.6.4
$ reana-client outputs  download greetings.txt --workflow=5b06633b-6a1e-4436-b309-9f887f12588b
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.99.100:31308
[DEBUG] Running find_module: netrc...
[DEBUG] Running load_module for netrc...
[DEBUG] Excluded netrc from translation
[DEBUG] Running find_module: shlex...
[DEBUG] Running load_module for shlex...
[DEBUG] Excluded shlex from translation
[WARNING] Failed to parse headers (url=http://192.168.99.100:31308/api/analyses/5b06633b-6a1e-4436-b309-9f887f12588b/workspace/outputs/greetings.txt?user=00000000-0000-0000-0000-000000000000&organization=default): [NoBoundaryInMultipartDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python3.6/site-packages/urllib3/connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python3.6/site-packages/urllib3/util/response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [NoBoundaryInMultipartDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
[INFO] greetings.txt binary file downloaded ... writing to ./outputs/
File greetings.txt downloaded to ./outputs/
$ workon reana-client-2.7
$ python --version
Python 2.7.14
$ reana-client outputs  download greetings.txt --workflow=5b06633b-6a1e-4436-b309-9f887f12588b
[INFO] REANA Server URL ($REANA_SERVER_URL) is: http://192.168.99.100:31308
[INFO] greetings.txt binary file downloaded ... writing to ./outputs/
File greetings.txt downloaded to ./outputs/
```

**Comment by diegodelemos** [comment]
@tiborsimko  should we move this to a different milestone since we only support Python 2.7 (Python 3 support is blocked see [herre](https://github.com/reanahub/reana-client/issues/17)).

**Comment by tiborsimko** [comment]
FYI seeing the traceback still, but the file was downloadable with 3.6.  Since we are releasing with 2.7, moving this to Someday.
